### ISSUE TITLE
Converter Failing on a Page

### ISSUE THREAD

**Issue by jkbellew** [pagekeytech/onenote-to-markdown#5]
I'm getting this error:
```
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\015_Enneagram_Personality_Result___Type_4w3.md
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\016_Five_Minute_Journal___Daily_Journal_Techniques_and_Tips.md
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\017_Vaccination_Card_3_shots.md
Traceback (most recent call last):
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 121, in <module>
    handle_element(onenote, child)
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 101, in handle_element
    handle_element(onenote, c2, os.path.join(path, safe_str(elem.attrib['name'])), i)
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 103, in handle_element
    hier2 = onenote.GetHierarchy(elem.attrib['ID'], win32.constants.hsPages, "")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Temp\gen_py\3.11\F2A7EE29-8BF6-4A6D-83F1-098E366C709Cx0x1x0\IApplication.py", line 63, in GetHierarchy
    return self._ApplyTypes_(1610743808, 1, (24, 0), ((8, 1), (3, 1), (16392, 2)), 'GetHierarchy', None,bstrStartNodeID
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\GitHub\onenote-to-markdown\.venv\Lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147023174, 'The RPC server is unavailable.', None, None)
!!!Error!!! Hint: Make sure OneNote is open first.
```

OneNote is open but something causes it to close causing the RPC error. Nothing gets written the desktop either. 

There needs to be some error handling. I'm reviewing the youtube video and seeing if I need to clear anything. I'm using OneNote for Windows 11 and everything is updated.

**Comment by stephengrice** [comment]
Can you send the page "Vaccination_Card_3_shots" or provide more information about what's on that page? Specifically, I'd assume there's some type of image on there - do you know what image type? (PNG, JPG, etc?)

**Comment by jkbellew** [comment]
It's an attached PDF and it displays that PDF. Couldn't there be an error routine that logs the page as not being imported and moves onto the next one?

**Comment by stephengrice** [comment]
Yep, try out the `page-err-handle` branch (#6) and see if it fixes your problem.

If not, try diving into the code and seeing if you can come up with a fix. I'll be happy to approve your PR.

Thanks!

**Comment by stephengrice** [comment]
Thanks for writing this up. Moving to the PageKey GitLab: https://gitlab.com/pagekey/edu/onenote-to-markdown/-/issues/3
